### ISSUE TITLE
tmux as default shell

### ISSUE THREAD

**Issue by DanielMueller1309** [quotengrote/dp_ausb_md#187]
Um beim einloggen auf der jeweiligen Konsole direkt ordentlich arbeiten zu können empfiehlt es sich gegebenenfalls beim einrichten via Ansible diese Task mit übernehmen zu lassen

**Comment by quotengrote** [comment]
Das sollte jeder Nutzer für sich selbst entscheiden.

Was ist z.B. noch mit nicht-interaktiven Nutzern, oder Script-Anmeldungen?(z.B. Cluster-Kommunikation in PVE über User: root).

Eine tmux-Rolle gibt es schon:
https://git.mgrote.net/mg/ansible/src/branch/master/roles/mgrote.tmux

**Comment by DanielMueller1309** [comment]
und wie wäre die idee diese rolle ein zu bauen und nur die variablen zu Dictionarys zu machen damit jeder selbst entscheiden kann in der groupvars all ob man sich bei tmux eintragen will? 
Scripte und co können dann ja über "mgmt user" und der normalen shell laufen.

**Comment by DanielMueller1309** [comment]
Aftreten von folgenden fehler beim ausrollen der neuen tmux rolle:
`fatal: [TLDNSM002]: FAILED! => {"msg": "The conditional check 'not stat_result.stat.exists' failed. The error was: error while evaluating conditional (not stat_result.stat.exists): 'dict object' has no attribute 'stat'\n\nThe error appears to be in '/home/daniel/ansible/roles/mgrote.tmux/tasks/main.yml': line 17, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: touch bashrc if it doesnt exist already ###{{ item.tmux_bashrc_destination }}\n    ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}`

die main sieht folgendermaßen aus:
```yml
---
  - name: install tmux packages
    become: yes
    ansible.builtin.package:
      name:
        - tmux
      state: present
      cache_valid_time: 360

  - name: Check if {{ item.tmux_bashrc_destination }} exists
    stat:
      path: "{{ item.tmux_bashrc_destination }}"
    register: stat_result
    with_items:
      - "{{ users_tmux }}"

  - name: touch bashrc if it doesnt exist already ###{{ item.tmux_bashrc_destination }}
    become: yes
    file:
      path: "{{ item.tmux_bashrc_destination }}"
      state: touch
    when: not stat_result.stat.exists
    with_items:
      - "{{ users_tmux }}"

  - name: download tmux.conf for "{{ item.username }}"
    get_url:
      url: "{{ item.tmux_downloadpath }}"
      dest: "{{ item.tmux_conf_destination }}"
      mode: '0664'
    when: item.tmux_allow|bool  == true
    with_items: "{{ users_tmux }}"

  - name: add tmux-session config to .bashrc
    become: yes
    ansible.builtin.blockinfile:
      path: "{{ item.tmux_bashrc_destination }}"
      block: |
        if command -v tmux &> /dev/null && [ -z "$TMUX" ]; then
        tmux attach -t {{ item.tmux_standardsession_name }} || tmux new -s {{ item.tmux_standardsession_name }}
        fi
    with_items: "{{ users_tmux }}"

```

für weitere details siehe: [tmux branch](https://github.com/quotengrote/dp_ausb_md/tree/tmux/ansible/roles/mgrote.tmux)
